name: logos

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  encrypt: '>=3.1.0'
  crypto: '>=2.0.6'
  dio: ^2.1.6
  cached_network_image: ^0.8.0
  flutter_bloc: ^0.13.0
  path_provider: ^0.5.0+1
  url_launcher: ^5.0.2
  sembast: ^1.15.4
  page_transition: ^1.1.0
  image_picker: ^0.6.0+8
  permission_handler: ^3.1.0
  file_picker: ^1.3.5
  auto_size_text: ^2.0.1
  flutter_map: any


dev_dependencies:

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png